[package]
name = "hothouse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6.1"
libmath = "0.1.4"
rand = "0.8.5"
itertools = "0.8.2"